### ISSUE TITLE
No syntax highlighting in helix

### ISSUE THREAD

**Issue by Aaronmacaron** [faldor20/tree-sitter-roc#14]
Hey, thank you so much for developing this project! I configured helix like you described in the README and helix correctly recognizes the configuration. This is the output of `hx --health roc`:

```
Configured language servers:
  ✓ roc_language_server: /nix/store/08kkx1biq2ccya7hrcp8dbjhbblwps6i-roc-0.0.1/bin/roc_language_server
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓

```

language-server integration works like expected which is awesome! Unfortunately I get no syntax highlighting in helix. Is this behaviour expected?

**Comment by faldor20** [comment]
Have you compiled the grammar? I see you're using nix so I'm not sure if that's possible without some special flake wizardry
Usually you run:
```bash
hx -g fetch
hx -g build
```
helix on nix builds all the gramars as individual nix derivations and them combines them somehow and I haven't done the PR into helix yet (something I should do)

Currently on my nix machine I acutually have it build via neovim, I run TSUpdate in neovim which builds the grammar properly (no idea why helix can't do this) and then i copy it into helix
```bash
cp ~/.local/share/nvim/lazy/nvim-treesitter/parser/roc.so ~/.config/helix/runtime/grammars/
```

Let me know how you get on, sorry, nix is such a pain sometimes :sweat:

**Comment by faldor20** [comment]
oh also you might have the wrong revision, i just realized there was a particular revision in the config, it should just be the latest commit: ac2cf031b1e25d7481586f54aa64136ff7e8f6fb

**Comment by Aaronmacaron** [comment]
Thank you so much! Changing to the latest commit and recompiling fixed the problem. By the way, how realistic is it that this repo will be merged into helix so that we don't have to manually configure helix for Roc?
