### ISSUE TITLE
Issues with certain strings and bangs

### ISSUE THREAD

**Issue by lboklin** [faldor20/tree-sitter-roc#19]
There appears to be an issue with strings in different contexts, and bangs when they occur in pipelines.
Here, a string is not highlighted:
![Screenshot_20240612_132102](https://github.com/faldor20/tree-sitter-roc/assets/6375669/a08c0b75-5f50-49a0-a661-10be4f479f5b)
here an interpolated string is not correctly highlighted:
![Screenshot_20240612_133353](https://github.com/faldor20/tree-sitter-roc/assets/6375669/d85cdf28-5e98-4f8a-9e09-e726987d105e)
here, bangs are inconsistently highlighted:
![Screenshot_20240612_133452](https://github.com/faldor20/tree-sitter-roc/assets/6375669/e07e52d7-f20a-4d0a-8b00-3bfc3d6dc09e)
but the interpolated string looks correct here:
![Screenshot_20240612_132542](https://github.com/faldor20/tree-sitter-roc/assets/6375669/c80a8328-bf1e-4ff1-815f-ad2158f1ec63)
![image](https://github.com/faldor20/tree-sitter-roc/assets/6375669/b61989a9-6e6a-4ba4-89a7-36cf9838f588)
![image](https://github.com/faldor20/tree-sitter-roc/assets/6375669/fc832cd9-fb81-49cd-af1f-ed192126ef37)
![image](https://github.com/faldor20/tree-sitter-roc/assets/6375669/a475d7e7-5e6a-4537-8d9c-6faf818a3281)

Edit: this is in Helix

**Comment by faldor20** [comment]
Thanks for your issue. I'll look into it shortly. :).
The strings issue is because of a change I made to highlight strings as other languages. I should have constrained it to a pre-approved list, which I will now do. 
The bangs, I'm not sure about and will investigate.

**Comment by faldor20** [comment]
Hey @lboklin I updated the highlights and the parser. 
Try building the parser and using the new queries and let me know how it goes

**Comment by smores56** [comment]
I've copied the majority of the code to text, here's what I've got:

```roc
app [main] {
    pf: platform "https://github.com/roc-lang/basic-webserver/releases/download/0.4.0/iAiYpbs5zdVB75golcg_YMtgexN3e2fwhsYPLPCeGzk.tar.br",
    html: "https://github.com/Hasnep/roc-html/releases/download/v0.6.0/IOyNfA4U_bCVBihrs95US9Tf5PGAWh3qvrBN4DRbK5c.tar.br",
}

import pf.Task exposing [Task]
import pf.Utc
import pf.Stdout
import pf.Http exposing [Request, Response]

main : Request -> Task Response []
main = \req ->
    # FIXME: this does not print anything
    date = Utc.now! |> Utc.toIso8601Str
    Stdout.line! "$(date) $(Http.methodToStr req.method) $(req.url)"

    Task.ok { status: 200, headers: [], body }

serviceUrl = \host, port ->
    when host is
        Nixbox -> Url.fromStr "http://192.168.1.41:$(Num.toStr port)"
        Nixtower -> Url.fromStr "http://192.168.1.31:$(Num.toStr port)"

example1 =
    Stdout.line! "http://192.168.1.31:$(Num.toStr port)"
    Stdout.test "http://192.168.1.31:$(Num.toStr port)"

example2 =
    test "http://192.168.1.31:$(Num.toStr port)"
```

**Comment by smores56** [comment]
When I go to the latest commit (a662513450e163dc2056603b1f426b4787aac0fd) and copy in the latest queries and build the grammar, I get this:

![Screenshot from 2024-06-21 16-53-12](https://github.com/faldor20/tree-sitter-roc/assets/22140449/f48ce61f-9bb6-4a8e-81fd-fecfca7fe678)

@faldor20 it seems as if highlighting is correct within the strings for the URL's, but the `platform` keyword in the app declaration is preventing the "basic-webserver" download URL from being highlighted properly, as was the case before.

**Comment by faldor20** [comment]
Thanks for checking that @smores56 , I'll take a look this evening when I'm back at my computer.

**Comment by faldor20** [comment]
I took a look, looks like it just wasn't given a highlight. Now it's set to be a string. should be all solved :)
